name: ESLint

on: [push]

jobs:
  run_linter:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # ESLint must be in `package.json`
      - name: Install Node.js dependencies
        run: npm i
      - name: Run tests
        run: npm test

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          files: src/
          eslint: true
